name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"

  pull_request:
    branches:
      - main

jobs:
  build:
    uses: your-org/github-workflows/.github/workflows/build-and-deploy-to-wporg.yml@main
    with:
      plugin-slug: holiday-mode-for-woocommerce
      deploy: true
    secrets: inherit